-- ================================================
-- Day 39 - SQL Learning Notes
-- Topic: EDA Project COMPLETED!
--        Measure Exploration, Magnitude Analysis
--        and Ranking Analysis
-- ================================================

-- ------------------------------------------------
-- WHAT I DID TODAY
-- ------------------------------------------------

-- Completed EDA Project fully today!
-- Completed Step 4 - Measure Exploration
-- Completed Step 5 - Magnitude Analysis
-- Completed Step 6 - Ranking Analysis
-- Learned about UNION ALL
-- Learned about Low and High Cardinality
-- Learned TOP keyword in SQL Server
-- Learned Subquery with alias requirement
-- EDA Project 100% Complete! 

-- ================================================
-- EDA PROJECT - DAY 3 - FINAL DAY
-- ================================================

-- Project Name: EDA Using SQL
-- Database: DataWarehouse
-- Status: COMPLETED 
-- Tables: customer, products, sales

USE datawarehouse;

-- ================================================
-- STEP 4 - MEASURES EXPLORATION
-- ================================================

-- Goal:
-- Calculate key metrics of the business
-- Find Big Numbers at highest aggregation
-- Understand the scale of the business

-- Find Total Sales
SELECT
    SUM(sales_amount) AS total_sales
FROM sales;

-- Find Total Items Sold
SELECT
    SUM(quantity) AS total_items_sold
FROM sales;

-- Find Average Selling Price
SELECT
    AVG(price) AS avg_selling_price
FROM sales;

-- Find Total Number of Orders
-- COUNT includes duplicates
SELECT
    COUNT(order_number) AS total_orders
FROM sales;

-- COUNT DISTINCT removes duplicates
SELECT
    COUNT(DISTINCT order_number) AS total_unique_orders
FROM sales;

-- Find Total Number of Products
SELECT
    COUNT(product_key)          AS total_products,
    COUNT(DISTINCT product_key) AS total_unique_products
FROM products;

-- Find Total Number of Customers
SELECT
    COUNT(customer_key) AS total_customers
FROM customer;

-- Find Customers Who Placed Orders
-- Only customers in sales table
SELECT
    COUNT(DISTINCT customer_key) AS customers_with_orders
FROM sales;

-- ------------------------------------------------
-- SQL TASK - Business Key Metrics Report
-- ------------------------------------------------

-- Generate report showing all key metrics
-- Using UNION ALL to combine all metrics
SELECT 'Total Sales'            AS measure_name,
       SUM(sales_amount)        AS measure_value
FROM sales
UNION ALL
SELECT 'Total Quantity',
       SUM(quantity)
FROM sales
UNION ALL
SELECT 'Average Price',
       AVG(price)
FROM sales
UNION ALL
SELECT 'Total Orders',
       COUNT(DISTINCT order_number)
FROM sales
UNION ALL
SELECT 'Total Products',
       COUNT(product_key)
FROM products
UNION ALL
SELECT 'Total Customers',
       COUNT(customer_key)
FROM customer;

-- UNION ALL Rule Learned Today:
-- Number of columns must match
-- Data types of columns must match
-- UNION ALL keeps all rows including duplicates
-- UNION removes duplicates

-- ================================================
-- STEP 5 - MAGNITUDE ANALYSIS
-- ================================================

-- Goal:
-- Compare measure values by categories
-- Understand importance of different categories
-- Formula = [Measure] by [Dimension]
-- Example = Total Sales by Country

-- Find Total Customers by Country
SELECT
    country,
    COUNT(DISTINCT customer_key) AS total_customers
FROM customer
GROUP BY country
ORDER BY total_customers DESC;

-- Find Total Customers by Gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM customer
GROUP BY gender
ORDER BY total_customers DESC;

-- Find Total Products by Category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM products
GROUP BY category
ORDER BY total_products DESC;

-- Find Average Cost in Each Category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM products
GROUP BY category
ORDER BY avg_cost DESC;

-- Find Total Revenue Generated by Each Category
SELECT
    p.category,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find Total Revenue Generated by Each Customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_revenue
FROM customer c
LEFT JOIN sales s
ON c.customer_key = s.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- Find Distribution of Sold Items by Country
SELECT
    country,
    SUM(quantity) AS total_sold_items
FROM customer c
LEFT JOIN sales s
ON c.customer_key = s.customer_key
GROUP BY country
ORDER BY total_sold_items DESC;

-- ------------------------------------------------
-- CARDINALITY CONCEPT LEARNED TODAY
-- ------------------------------------------------

-- LOW CARDINALITY DIMENSION
-- Dimension with FEW unique values
-- Examples: country, gender, category
-- Good for GROUP BY analysis
-- Easy to visualize in charts

-- HIGH CARDINALITY DIMENSION
-- Dimension with LARGE number of unique values
-- Examples: product, customer, address
-- Harder to visualize directly
-- Use TOP N to limit results

-- ================================================
-- STEP 6 - RANKING ANALYSIS
-- ================================================

-- Goal:
-- Order dimension values by measure
-- Find Top N and Bottom N performers
-- Formula = Rank [Dimension] by [Measure]

-- Method 1 - Using TOP keyword
-- TOP keyword in SQL Server = LIMIT in MySQL

-- Find Top 5 Products by Highest Revenue
SELECT TOP 5
    p.product_name,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- Find 5 Worst Performing Products
SELECT TOP 5
    p.product_name,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;

-- Find Top 5 Best Performing Subcategories
SELECT TOP 5
    p.subcategory,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN products p
ON s.product_key = p.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC;

-- ------------------------------------------------
-- Method 2 - Using Window Functions
-- More flexible with extra details
-- ------------------------------------------------

-- Find Top 5 Products using ROW_NUMBER
SELECT *
FROM
(
    SELECT
        p.product_name,
        SUM(s.sales_amount)     AS total_revenue,
        ROW_NUMBER() OVER(
            ORDER BY SUM(s.sales_amount) DESC
        )                       AS rank_products
    FROM sales s
    LEFT JOIN products p
    ON s.product_key = p.product_key
    GROUP BY p.product_name
) t                             -- alias t is required in SQL Server
WHERE rank_products <= 5;       -- every subquery needs an alias

-- Important Note Learned Today:
-- In SQL Server every derived table
-- subquery in FROM clause MUST have alias
-- Without alias SQL Server gives error
-- alias t after closing bracket is required

-- Find Top 10 Customers by Revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN customer c
ON c.customer_key = s.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- Find Top 3 Customers with Fewest Orders
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM sales s
LEFT JOIN customer c
ON c.customer_key = s.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders ASC;

-- ================================================
-- ALL EDA STEPS COMPLETED
-- ================================================

-- Step 1 = Database Exploration      ✅
--   INFORMATION_SCHEMA explored
-- Step 2 = Dimension Exploration     ✅
--   Countries categories products found
-- Step 3 = Date Exploration          ✅
--   Order shipping customer age found
-- Step 4 = Measure Exploration       ✅
--   Total sales orders customers found
-- Step 5 = Magnitude Analysis        ✅
--   Metrics by category country found
-- Step 6 = Ranking Analysis          ✅
--   Top bottom performers found

-- ================================================
-- KEY LEARNINGS FROM EDA PROJECT
-- ================================================

-- UNION ALL
--   Combines results of multiple queries
--   Number and type of columns must match
--   Keeps all rows including duplicates

-- LOW CARDINALITY
--   Few unique values in dimension
--   Good for grouping and charts

-- HIGH CARDINALITY
--   Many unique values in dimension
--   Use TOP N to limit output

-- TOP keyword in SQL Server
--   Same as LIMIT in MySQL
--   TOP 5 = show only 5 rows
--   Always use with ORDER BY

-- Subquery Alias Requirement
--   Every subquery in FROM clause
--   must have an alias in SQL Server
--   Use letter t or any name after bracket

-- ================================================
-- SUMMARY - WHAT I DID TODAY
-- ================================================

-- Completed EDA Project fully!
-- All 6 steps completed successfully
-- Learned UNION ALL for metrics report
-- Learned Cardinality concept
-- Learned TOP vs LIMIT difference
-- Learned subquery alias requirement
-- EDA Project ready for GitHub upload!

-- ================================================
-- TOMORROW I WILL
-- ================================================

-- Write README for EDA Project
-- Upload EDA Project to SQL-Projects folder
-- Start Data Cleaning with SQL
-- Learn how to handle NULL values
-- Learn how to remove duplicates